version: 0.2

env:
  variables:
    PACKAGE: "github.com/intelematics/terraform-provider-cloudconformity"
    GO_HOME: "/go"
    IMAGE_REPO_NAME: "terraform-provider-cloudconformity"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo CODEBUILD_SOURCE_VERSION - $CODEBUILD_SOURCE_VERSION
      - echo CODEBUILD_WEBHOOK_BASE_REF - $CODEBUILD_WEBHOOK_BASE_REF
      - echo CODEBUILD_WEBHOOK_HEAD_REF - $CODEBUILD_WEBHOOK_HEAD_REF
      - echo CODEBUILD_WEBHOOK_TRIGGER - $CODEBUILD_WEBHOOK_TRIGGER
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - if [[ $CODEBUILD_WEBHOOK_HEAD_REF == *"feature"* ]]; then
        echo "It's there!"
        fi
      - echo $($CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f3)
      - echo Create dir in GOPATH for sources...
      - mkdir -p $GO_HOME/src/$PACKAGE
      - echo Copy source files into GOPATH...
      - echo cp -a ${CODEBUILD_SRC_DIR}/.  $GO_HOME/src/$PACKAGE
      - cp -a ${CODEBUILD_SRC_DIR}/.  $GO_HOME/src/$PACKAGE
      - cd $GO_HOME/src/$PACKAGE
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the provider...
      - cd $GO_HOME/src/$PACKAGE && go build -o $GO_HOME/src/$PACKAGE/docker/terraform-provider-cloudconformity
      - cd docker
      - echo Building docker image...
      - docker build -t $IMAGE_REPO_NAME:1 .
      - docker tag $IMAGE_REPO_NAME:1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME